# bridge_config.yaml
-
  ros_topic: /cmd_vel
  gz_topic: /model/turtlebot3_waffle/cmd_vel
  ros_type: "geometry_msgs/msg/Twist"
  gz_type: "gz.msgs.Twist"
  direction: ROS_TO_GZ
-
  ros_topic: /odom
  gz_topic: /model/turtlebot3_waffle/odometry
  ros_type: "nav_msgs/msg/Odometry"
  gz_type: "gz.msgs.Odometry"
  direction: GZ_TO_ROS
-
  ros_topic: /scan
  gz_topic: /model/turtlebot3_waffle/scan
  ros_type: "sensor_msgs/msg/LaserScan"
  gz_type: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS
-
  ros_topic: /joint_states
  gz_topic: /model/turtlebot3_waffle/joint_states
  ros_type: "sensor_msgs/msg/JointState"
  gz_type: "gz.msgs.JointState"
  direction: GZ_TO_ROS
